[project]
name = "basic-mcp-server"
version = "0.1.0"
description = "Basic MCP server created using FastMCP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.14.0",
]
